Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 260, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 557, in index
    app_list = self.get_app_list(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 541, in get_app_list
    app_dict = self._build_app_dict(request, app_label)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\admin\sites.py", line 487, in _build_app_dict
    perms = model_admin.get_model_perms(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\admin\options.py", line 781, in get_model_perms
    "add": self.has_add_permission(request),
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\admin\options.py", line 574, in has_add_permission
    return request.user.has_perm("%s.%s" % (opts.app_label, codename))
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\users\models.py", line 59, in has_perm
    return self.is_admin
           ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'is_admin'
"GET /admin/ HTTP/1.1" 500 121027
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\deprecation.py", line 128, in __call__
    response = self.process_request(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.OperationalError: (1054, "Unknown column 'users_user.is_superuser' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 445, in run_validation
    value = self.validate(value)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.OperationalError: (1054, "Unknown column 'users_user.is_superuser' in 'field list'")
"POST /api/token/ HTTP/1.1" 500 238168
Internal Server Error: /api/token/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.OperationalError: (1054, "Unknown column 'users_user.is_superuser' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 445, in run_validation
    value = self.validate(value)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 73, in validate
    data = super().validate(attrs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework_simplejwt\serializers.py", line 54, in validate
    self.user = authenticate(**authenticate_kwargs)
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.OperationalError: (1054, "Unknown column 'users_user.is_superuser' in 'field list'")
"POST /api/token/ HTTP/1.1" 500 238168
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 45, in get_operation
    responses = self.get_responses()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 180, in get_responses
    response_serializers = self.get_response_serializers()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 235, in get_response_serializers
    responses = self.get_default_responses()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 211, in get_default_responses
    default_schema = self.serializer_to_schema(default_schema) or ''
                     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ~~~~~~~~~~~~~~~~~~~~~^
        self.field_inspectors, 'get_schema', serializer, {'field_inspectors': self.field_inspectors}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 49, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ~~~~~~~~~~~~~~~~~~~~~^
        self.field_inspectors, 'field_to_swagger_object', field, {'field_inspectors': self.field_inspectors},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 140, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 109, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'updated_by_username' was declared on serializer DictionarySerializer, but has not been included in the 'fields' option.
"GET /swagger/?format=openapi HTTP/1.1" 500 221185
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 45, in get_operation
    responses = self.get_responses()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 180, in get_responses
    response_serializers = self.get_response_serializers()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 235, in get_response_serializers
    responses = self.get_default_responses()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 211, in get_default_responses
    default_schema = self.serializer_to_schema(default_schema) or ''
                     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ~~~~~~~~~~~~~~~~~~~~~^
        self.field_inspectors, 'get_schema', serializer, {'field_inspectors': self.field_inspectors}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 49, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ~~~~~~~~~~~~~~~~~~~~~^
        self.field_inspectors, 'field_to_swagger_object', field, {'field_inspectors': self.field_inspectors},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 140, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 109, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'updated_by_username' was declared on serializer DictionarySerializer, but has not been included in the 'fields' option.
"GET /swagger/?format=openapi HTTP/1.1" 500 221185
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\views.py", line 112, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 276, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
                    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 482, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\generators.py", line 524, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 45, in get_operation
    responses = self.get_responses()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 180, in get_responses
    response_serializers = self.get_response_serializers()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 235, in get_response_serializers
    responses = self.get_default_responses()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\view.py", line 211, in get_default_responses
    default_schema = self.serializer_to_schema(default_schema) or ''
                     ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 438, in serializer_to_schema
    return self.probe_inspectors(
           ~~~~~~~~~~~~~~~~~~~~~^
        self.field_inspectors, 'get_schema', serializer, {'field_inspectors': self.field_inspectors}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 49, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
           ~~~~~~~~~~~~~~~~~~~~~^
        self.field_inspectors, 'field_to_swagger_object', field, {'field_inspectors': self.field_inspectors},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        swagger_object_type=swagger_object_type, use_references=use_references, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 140, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\openapi.py", line 685, in setdefault
    ret = maker()
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\drf_yasg\inspectors\field.py", line 109, in make_schema_definition
    for property_name, child in serializer.fields.items():
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "C:\Users\phara\OneDrive\Desktop\Django_project\dictionary_project\venv\Lib\site-packages\rest_framework\serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'word_type_kh_display' was declared on serializer DictionarySerializer, but has not been included in the 'fields' option.
"GET /swagger/?format=openapi HTTP/1.1" 500 221147
